### ISSUE TITLE
Unable to upgrade to beta 7 with brew

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/homebrew-den#1]
Hi,
I tried to upgrade to the latest beta and got the issue:
![image](https://user-images.githubusercontent.com/1873745/190347114-a90f163b-66f6-490d-b78c-6f0432ab4ab5.png)

**Comment by navarr** [comment]
Strange that the shasum from the automated system would be different.

I'll get that fixed this AM and comment again once it is.

**Comment by navarr** [comment]
Fixed.
